version: '3.9'

services:
    db:
        image: mysql:5.7
        container_name: api_mysql
        volumes:
            - ./db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: qw#rty!(*#
            MYSQL_DATABASE: api
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        networks:
            - api-network
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        container_name: api_phpmyadmin 
        restart: always
        ports:
            - '8061:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
        networks:
            - api-network 
    web:
        image: nginx:latest
        container_name: api_nginx  
        ports:
            - "8060:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - api-network
    php:
        image: php:fpm
        container_name: api_php
        command:
            - /bin/sh
            - -c
            - |
               docker-php-ext-install mysqli pdo pdo_mysql
               php-fpm
        volumes:
            - ./code:/code
        networks:
            - api-network

networks:
    api-network:
        driver: bridge
    #wordpress_wpsite:
    #    external: true
